name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.15.0'
      - run: npm ci
      - run: npm run test

  solidity-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./samples/solidity
    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.15.0'
      - run: npm ci
      - run: npm run compile
      - run: npm run test
